//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: psaiCoreEntities.proto
namespace psai
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoBuf_AudioData")]
  public partial class ProtoBuf_AudioData : global::ProtoBuf.IExtensible
  {
    public ProtoBuf_AudioData() {}
    

    private string _filename = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string filename
    {
      get { return _filename; }
      set { _filename = value; }
    }

    private int _sampleRate = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sampleRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sampleRate
    {
      get { return _sampleRate; }
      set { _sampleRate = value; }
    }

    private int _sampleCountTotal = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sampleCountTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sampleCountTotal
    {
      get { return _sampleCountTotal; }
      set { _sampleCountTotal = value; }
    }

    private int _sampleCountPrebeat = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sampleCountPrebeat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sampleCountPrebeat
    {
      get { return _sampleCountPrebeat; }
      set { _sampleCountPrebeat = value; }
    }

    private int _sampleCountPostbeat = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sampleCountPostbeat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sampleCountPostbeat
    {
      get { return _sampleCountPostbeat; }
      set { _sampleCountPostbeat = value; }
    }

    private float _bpm = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bpm", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float bpm
    {
      get { return _bpm; }
      set { _bpm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoBuf_Snippet")]
  public partial class ProtoBuf_Snippet : global::ProtoBuf.IExtensible
  {
    public ProtoBuf_Snippet() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _intensity;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"intensity", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float intensity
    {
      get { return _intensity; }
      set { _intensity = value; }
    }

    private int _snippet_type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"snippet_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int snippet_type
    {
      get { return _snippet_type; }
      set { _snippet_type = value; }
    }

    private int _theme_id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"theme_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int theme_id
    {
      get { return _theme_id; }
      set { _theme_id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private psai.ProtoBuf_AudioData _audio_data = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"audio_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public psai.ProtoBuf_AudioData audio_data
    {
      get { return _audio_data; }
      set { _audio_data = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _follower_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"follower_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> follower_id
    {
      get { return _follower_id; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _follower_compatibility = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(7, Name=@"follower_compatibility", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> follower_compatibility
    {
      get { return _follower_compatibility; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoBuf_Theme")]
  public partial class ProtoBuf_Theme : global::ProtoBuf.IExtensible
  {
    public ProtoBuf_Theme() {}
    

    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int _themeType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"themeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int themeType
    {
      get { return _themeType; }
      set { _themeType = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private float _intensityAfterRest = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"intensityAfterRest", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float intensityAfterRest
    {
      get { return _intensityAfterRest; }
      set { _intensityAfterRest = value; }
    }

    private int _musicPhaseSecondsAfterRest = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"musicPhaseSecondsAfterRest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int musicPhaseSecondsAfterRest
    {
      get { return _musicPhaseSecondsAfterRest; }
      set { _musicPhaseSecondsAfterRest = value; }
    }

    private int _musicPhaseSecondsGeneral = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"musicPhaseSecondsGeneral", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int musicPhaseSecondsGeneral
    {
      get { return _musicPhaseSecondsGeneral; }
      set { _musicPhaseSecondsGeneral = value; }
    }

    private int _restSecondsMin = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"restSecondsMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restSecondsMin
    {
      get { return _restSecondsMin; }
      set { _restSecondsMin = value; }
    }

    private int _restSecondsMax = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"restSecondsMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restSecondsMax
    {
      get { return _restSecondsMax; }
      set { _restSecondsMax = value; }
    }

    private float _weightingSwitchGroups = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"weightingSwitchGroups", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float weightingSwitchGroups
    {
      get { return _weightingSwitchGroups; }
      set { _weightingSwitchGroups = value; }
    }

    private float _weightingIntensityVsVariety = default(float);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"weightingIntensityVsVariety", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float weightingIntensityVsVariety
    {
      get { return _weightingIntensityVsVariety; }
      set { _weightingIntensityVsVariety = value; }
    }

    private float _weightingPlaycountVsRandom = default(float);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"weightingPlaycountVsRandom", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float weightingPlaycountVsRandom
    {
      get { return _weightingPlaycountVsRandom; }
      set { _weightingPlaycountVsRandom = value; }
    }

    private int _priority = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoBuf_PsaiCoreSoundtrack")]
  public partial class ProtoBuf_PsaiCoreSoundtrack : global::ProtoBuf.IExtensible
  {
    public ProtoBuf_PsaiCoreSoundtrack() {}
    
    private readonly global::System.Collections.Generic.List<psai.ProtoBuf_Theme> _themes = new global::System.Collections.Generic.List<psai.ProtoBuf_Theme>();
    [global::ProtoBuf.ProtoMember(1, Name=@"themes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<psai.ProtoBuf_Theme> themes
    {
      get { return _themes; }
    }
  
    private readonly global::System.Collections.Generic.List<psai.ProtoBuf_Snippet> _snippets = new global::System.Collections.Generic.List<psai.ProtoBuf_Snippet>();
    [global::ProtoBuf.ProtoMember(2, Name=@"snippets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<psai.ProtoBuf_Snippet> snippets
    {
      get { return _snippets; }
    }
  

    private string _audioformat = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"audioformat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string audioformat
    {
      get { return _audioformat; }
      set { _audioformat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}