// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDE2DListItemKeys
    {
        public static string TwoDList_DevItem = "DevItem";
        public static string TwoDListCustom_custom = "custom";
    }
}