// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
// 
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEReadSceneItemKeys
    {
        public static string ReadScene_test_data = "test_data";
        public static string ReadSceneUnityTypes_unity_types_data = "unity_types_data";
        public static string ReadSceneCustom_custom_1 = "custom_1";
        public static string ReadSceneCustom_custom_2 = "custom_2";
        public static string ReadSceneCustom_custom_3 = "custom_3";
    }
}