// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string WeaponItem_Knife = "Knife";
        public static string DefenseItem_ManDrake = "ManDrake";
        public static string DefenseItem_Paperball = "Paperball";
    }
}
